# config.yaml
# database:
#   username: root
#   password: DOIFJNA23#
#   host: 121.5.73.12
#   port: 3344
#   dbname: yiliao

 database:
   username: root
   password: qwer1234,
   host: 1.12.242.253
   port: 3306
   dbname: yiliao

#database:
#  username: root
#  password: 123456
#  host: 127.0.0.1
#  port: 3306
#  dbname: yiliao